{% set name = "xarray" %}
{% set version = "2024.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-{{ version }}.tar.gz
  sha256: e0eb1cb265f265126795f388ed9591f3c752f2aca491f6c0576711fd15b708f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.9
    - numpy >=1.23
    - pandas >=2.0
    - packaging >=23.1
  run_constrained:
    - bottleneck >=1.3
    - cartopy >=0.21
    - cftime >=1.6
    - dask-core >=2023.4
    - distributed >=2023.4
    - flox >=0.7
    - h5netcdf >=1.1
    - h5py >=3.8
    - hdf5 >=1.12
    - iris >=3.4
    - matplotlib-base >=3.7
    - nc-time-axis >=1.4
    - netcdf4 >=1.6.0
    - numba >=0.56
    - pint >=0.22
    - scipy >=1.10
    - seaborn >=0.12
    - sparse >=0.14
    - toolz >=0.12
    - zarr >=2.14

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - dcherian
