{% set name = "xarray" %}
{% set version = "2025.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray-{{ version }}.tar.gz
  sha256: c521c6c1b806fc8e5c9b1bed85d69ce950fd6d2668507d4dd02850787b4c84f2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.24
    - packaging >=23.2
    - pandas >=2.1
    - typing_extensions
  run_constrained:
    - bottleneck >=1.3
    - cartopy >=0.22
    - cftime >=1.6
    - dask-core >=2023.11
    - distributed >=2023.11
    - flox >=0.7
    - h5netcdf >=1.3
    - h5py >=3.8
    - hdf5 >=1.12
    - iris >=3.7
    - matplotlib-base >=3.8
    - nc-time-axis >=1.4
    - netcdf4 >=1.6.0
    - numba >=0.57
    - pint >=0.22
    - scipy >=1.11
    - seaborn-base >=0.13
    - sparse >=0.14
    - toolz >=0.12
    - zarr >=2.16

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - dcherian
    - keewis
    - TomNicholas
    - kmuehlbauer
