{% set version = "0.12.2" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: 3a9536b5bc4eac2f4689c4ec8308f68df7e3277579499dde208031d8faf79772

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - numpy >=1.12
    - pandas >=0.19.2

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: 'N-D labeled arrays and datasets in Python.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
