{% set version = "2023.2.0" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: aa760500a2d8f8be8efd8f3b27a94b2af3b0a8c2c037347d595eaf6ff09d8a77

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm

  run:
    - python >=3.8
    - numpy >=1.20
    - pandas >=1.3
    - packaging >=21.3

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
