{% set name = "xarray" %}
{% set version = "2023.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-{{ version }}.tar.gz
  sha256: aa760500a2d8f8be8efd8f3b27a94b2af3b0a8c2c037347d595eaf6ff09d8a77

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.9
    - numpy >=1.21
    - pandas >=1.4
    - packaging >=21.3
  run_constrained:
    - bottleneck >=1.3
    - cartopy >=0.20
    - cftime >=1.5
    - dask-core >=2022.1
    - distributed >=2022.1
    - flox >=0.5
    - h5netcdf >=0.13
    - h5py >=3.6
    - hdf5 >=1.12
    - iris >=3.1
    - matplotlib-base >=3.5
    - nc-time-axis >=1.4
    - netcdf4 >=1.5.7
    - numba >=0.55
    - pint >=0.18
    - rasterio >=1.2
    - scipy >=1.7
    - seaborn >=0.11
    - sparse >=0.13
    - toolz >=0.11
    - zarr >=2.10

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
