{% set version = "0.9.0" %}

package:
  name: xarray
  version: {{ version }}

source:
  fn: xarray-{{ version }}.tar.gz
  url: https://github.com/pydata/xarray/archive/v{{ version }}.tar.gz
  sha256: 05a1ee48cd887ff738c8451fcfb9408103f714df94f16cc944b1c160b4064f95

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - netcdf4
    - scipy
    - bottleneck
    - dask >=0.6
    - h5netcdf
    - cyordereddict  # [not py>=35]

test:
  imports:
    - xarray
    - xarray.backends
    - xarray.core
    - xarray.tests
  requires:
    - pytest
  commands:
    - pytest --pyargs xarray -v

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: 'N-D labeled arrays and datasets in Python.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
