{% set name = "xarray" %}
{% set version = "2025.9.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray-{{ version }}.tar.gz
  sha256: 7dd6816fe0062c49c5e9370dd483843bc13e5ed80a47a9ff10baff2b51e070fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77.0.3
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - packaging >=24.1
    - pandas >=2.2
  run_constrained:
    - bottleneck >=1.4
    - cartopy >=0.23
    - cftime >=1.6
    - dask-core >=2024.6
    - distributed >=2024.6
    - flox >=0.9
    - h5netcdf >=1.3
    - h5py >=3.11
    - hdf5 >=1.14
    - iris >=3.9
    - matplotlib-base >=3.8
    - nc-time-axis >=1.4
    - netcdf4 >=1.6.0
    - numba >=0.60
    - pint >=0.24
    - scipy >=1.13
    - seaborn-base >=0.13
    - sparse >=0.15
    - toolz >=0.12
    - zarr >=2.18

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - dcherian
    - keewis
    - TomNicholas
    - kmuehlbauer
