{% set version = "2022.6.0" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: 1028d198493f66bb15bd35dcfdd11defd831cbee3af6589fff16f41bddd67e84

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm

  run:
    - python >=3.8
    - numpy >=1.19
    - pandas >=1.2
    - packaging >=20.0

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
