{% set version = "2022.3.0" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: 398344bf7d170477aaceff70210e11ebd69af6b156fe13978054d25c48729440

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm

  run:
    - python >=3.8
    - numpy >=1.18
    - pandas >=1.1
    - importlib_metadata
    - typing_extensions >=3.7
    - packaging >=20.0

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
