{% set name = "xarray" %}
{% set version = "2023.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-{{ version }}.tar.gz
  sha256: 4565dbc890de47e278346c44d6b33bb07d3427383e077a7ca8ab6606196fd433

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.9
    - numpy >=1.22
    - pandas >=1.4
    - packaging >=21.3
  run_constrained:
    - bottleneck >=1.3
    - cartopy >=0.20
    - cftime >=1.6
    - dask-core >=2022.7
    - distributed >=2022.7
    - flox >=0.5
    - h5netcdf >=1.0
    - h5py >=3.6
    - hdf5 >=1.12
    - iris >=3.2
    - matplotlib-base >=3.5
    - nc-time-axis >=1.4
    - netcdf4 >=1.6.0
    - numba >=0.55
    - pint >=0.19
    - scipy >=1.8
    - seaborn >=0.11
    - sparse >=0.13
    - toolz >=0.12
    - zarr >=2.12

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - dcherian
