{% set version = "0.9.3" %}

package:
  name: xarray
  version: {{ version }}

source:
  fn: xarray-{{ version }}.tar.gz
  url: https://github.com/pydata/xarray/archive/v{{ version }}.tar.gz
  sha256: 4394e467ea3a85acf8257dd07830b53eb2796b3a404813a19abeb1215f9feca0

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - netcdf4
    - scipy
    - bottleneck
    - dask >=0.6
    - h5netcdf
    - cyordereddict  # [not py>=35]

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: 'N-D labeled arrays and datasets in Python.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
