{% set version = "0.11.1" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: 0289fe73eb2b0a4bf3e0c670fc232690f7b00b374d4280de0f0faa9c3801b509

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - numpy >=1.12
    - pandas >=0.19.2

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: 'N-D labeled arrays and datasets in Python.'

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
