{% set version = "0.20.0" %}

package:
  name: xarray
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray/xarray-{{ version }}.tar.gz
  sha256: 8ea93274868f78c46332fc3b75f4628f6d99e59a0315e294a99397ad1eb777a5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm

  run:
    - python >=3.7
    - numpy >=1.17
    - pandas >=1.0
    - setuptools >=40.4

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pytest

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
