{% set name = "xarray" %}
{% set version = "2024.7.0" %}
{% set min_python = "python >=3.9" %}

# handle undefined PYTHON in `noarch: generic` outputs
{% if PYTHON is not defined %}{% set PYTHON = "$PYTHON" %}{% endif %}

package:
  name: xarray-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-{{ version }}.tar.gz
  sha256: 4cae512d121a8522d41e66d942fb06c526bc1fd32c2c181d5fe62fe65b671638

build:
  noarch: python
  number: 1

outputs:
  - name: xarray-core
    build:
      noarch: generic
    requirements:
      host:
        - {{ min_python }}
        - setuptools >=42
        - setuptools-scm >=7
        - pip
      run:
        - {{ min_python }}
        - numpy >=1.23
        - packaging >=23.1
        - pandas >=2.0
    test:
      imports:
        - xarray
      requires:
        - pip
      commands:
        - pip check
  - name: xarray
    build:
      noarch: generic
    requirements:
      host:
        - {{ min_python }}
        - setuptools >=42
        - setuptools-scm >=7
        - pip
      run:
        - {{ min_python }}
        - {{ pin_subpackage("xarray-core", exact=True) }}
        # accel
        - flox >=0.7
        - opt_einsum
        - numbagg
        # io & cloud
        - fsspec
        - netcdf4 >=1.6.0
        - zarr >=2.14
        # plotting
        - matplotlib-base >=3.7
        # misc
        - pooch
      run_constrained:
        - bottleneck >=1.3
        - cartopy >=0.21
        - cftime >=1.6
        - dask-core >=2023.4
        - distributed >=2023.4
        - h5netcdf >=1.1
        - h5py >=3.8
        - hdf5 >=1.12
        - iris >=3.4
        - nc-time-axis >=1.4
        - numba >=0.56
        - pint >=0.22
        - scipy >=1.10
        - seaborn >=0.12
        - sparse >=0.14
        - toolz >=0.12
    test:
      imports:
        - xarray
        - xarray.backends
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - dcherian
    - keewis
    - TomNicholas
