{% set name = "xarray" %}
{% set version = "2023.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xarray-{{ version }}.tar.gz
  sha256: 9f0f7e3402037c6611e802662b4374ddf55985a725bfc18dc2325cebdc06d4e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.9
    - numpy >=1.21
    - pandas >=1.4
    - packaging >=21.3

test:
  imports:
    - xarray
    - xarray.backends
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pydata/xarray
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
