schema_version: 1

context:
  name: xarray
  version: "2025.10.1"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/xarray-${{ version }}.tar.gz
  sha256: 3c2b5ad7389825bd624ada5ff26b01ac54b1aae72e2fe0d724d81d40a2bf5785

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77.0.3
    - setuptools-scm >=8
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.26
    - packaging >=24.1
    - pandas >=2.2
  run_constraints:
    - bottleneck >=1.4
    - cartopy >=0.23
    - cftime >=1.6
    - dask-core >=2024.6
    - distributed >=2024.6
    - flox >=0.9
    - h5netcdf >=1.3
    - h5py >=3.11
    - hdf5 >=1.14
    - iris >=3.9
    - matplotlib-base >=3.8
    - nc-time-axis >=1.4
    - netcdf4 >=1.6.0
    - numba >=0.60
    - pint >=0.24
    - scipy >=1.13
    - seaborn-base >=0.13
    - sparse >=0.15
    - toolz >=0.12
    - zarr >=2.18

tests:
  - python:
      imports:
        - xarray
        - xarray.backends
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: N-D labeled arrays and datasets in Python.
  homepage: https://github.com/pydata/xarray

extra:
  recipe-maintainers:
    - jhamman
    - ocefpaf
    - shoyer
    - dcherian
    - keewis
    - TomNicholas
    - kmuehlbauer
